import streamlit as st
import plotly.graph_objects as go
import numpy as np
import torch
from botorch.acquisition.analytic import LogNoisyExpectedImprovement
from botorch.optim import optimize_acqf
import os

from problems.approximations import I_porod
from core.models.BO_model import chi2_final_intensity_spheroid_BO_single,chi2_final_intensity_spheroid_BO_double,chi2_nano_intensity_spheroid_BO_double,chi2_nano_intensity_spheroid_BO_single
from core.optimizer.Levenberg_Marquardt import LM_optimize, LM_optimize_nostop, LM_joint_optimize
from core.acquisition.acquisition_functions import build_model
from core.models.assembled_problem import final_intensity_spheroid,nano_intensity_spheroid
from app.utilities.cache_generator import get_model_config
from core.utils.helper_functions import log_chi2_red_variance
from core.models.assembled_problem import final_intensity_spheroid,nano_intensity_spheroid,double_intensity_spheroid,single_intensity_spheroid,double_intensity_spheroid_mag, single_intensity_spheroid_mag